### PR TITLE
feat(sendfunction): created a function sendFunction to react to a message

### PR DESCRIPTION
**Pull request by Luisotee**
This is my first PR to a public repository, so if I did something wrong please tell me.

I added a function to react to a message in whatsapp like this:
image

An example of the function in use:

```
async function onNewMessage(message: Message) {
  console.log("New message received:", message);
  sender.sendReaction(message.from, "😍", message.id);
}
```

### Pull-Request Checklist

- [x] Code is up-to-date with the `main` branch
- [x] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [ ] There are new or updated unit tests validating the change
- [ ] Documentation has been updated to reflect this change
- [x] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by j05u3** [comment]
awesome 🙌

**Comment by j05u3** [comment]
Just did a small test with Monaguillo.org, looks great thanks 🎉

image

**Comment by Luisotee** [comment]
Maybe an idea for you, in my bot I use it to tell the user wether his message is completed, failed, in queue or processing:

image

**Comment by j05u3** [comment]
> Maybe an idea for you, in my bot I use it to tell the user wether his message is completed, failed, in queue or processing:
> 
> image

Yeah, may be useful in my bot too, thank you, for now I'm focusing on sustainability ✌️

**Pull request merged**
