### PR TITLE
feat(createbot.ts, createbot.types.ts, messages.types.ts): support fo…

### PR DESCRIPTION
**Pull request by RyzorBent**
…r product and catalog messages

Add support for product and catalog messages

- Implement new functions: sendProduct, sendProductList, and sendCatalog
- Enable sending interactive product and catalog messages via WhatsApp Cloud API
- Update MessageSender interface to include new functions
- Add corresponding types for product and catalog messages
- Update README with new features and API usage documentation
- Enhance library capabilities for e-commerce use cases

### Pull-Request Checklist

- [x] Code is up-to-date with the `main` branch
- [ ] `npm run lint` passes with this change
- [x] `npm run test` passes with this change
- [ ] This pull request links relevant issues as `Fixes #0000`
- [x] There are new or updated unit tests validating the change
- [x] Documentation has been updated to reflect this change
- [x] The new commits follow conventions outlined in the [conventional commit spec](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by RyzorBent** [comment]
Realised that i missed an entry in `src/expressRouter.ts` --> ` case 'order':`. Pushing a fix

**Comment by RyzorBent** [comment]
Hi @j05u3, Any feedback on this pull req, is there perhaps something i'm missing that i need to correct?

**Comment by j05u3** [comment]
Sorry, I missed your comment @RyzorBent. I just took a look at your code and it looks good 👍. If you tested it locally or in some way maybe you can send some screenshots of it working 🙏, otherwise if you tell me that you are certain that it works then we can merge it I'd say 👍

**Comment by RyzorBent** [comment]
Morning @j05u3, ... here is a screen cast of the bot working with new code, everything should work fine :)
https://drive.google.com/file/d/1v9rH9yjqPVJWP5KYbugAgdHAujXwIpwC/view?usp=drive_link

**Comment by j05u3** [comment]
Hi @RyzorBent, I just requested asked  🙏

**Comment by j05u3** [comment]
Hi @RyzorBent , I just saw the video, it looks good. Let's merge then 🙌🎉

**Comment by RyzorBent** [comment]
Hi @j05u3,I think you can merge on your side. as i don't have powers to merge. 🤗

**Comment by j05u3** [comment]
Oh, I'm sorry, will do now then 🙏🙌

**Pull request merged**
